services:
  App\Services\ServicesGenerator:
    calls:
      - [setLogger, ['@logger']]
    decoration_priority: 1

  App\Services\ServicesGeneratorNew:

  app.service_generator: '@App\Services\ServicesGenerator'

  App\Services\ServicesGeneratorInterface: '@App\Services\ServicesGeneratorNew'


  App\Api\ParamConverter\StreetParamConverter:
    tags:
      - { name: request.param_converter, converter: get_street }
    arguments:
      - '@App\Repository\StreetRepository'

  App\Services\Security\TokenAuthenticator:
    arguments:
      - '@App\Repository\UserRepository'
      - '@App\Services\JwtAuth\ExtractPayloadInterface'

  App\Services\Security\PasswordGenerator:
    arguments:
      - '%env(APP_SECRET)%'

  App\Services\JwtAuth\JwtGenerator:
    arguments:
      - '%env(APP_SECRET)%'
    public: false

  App\Services\JwtAuth\JwtGeneratorInterface: '@App\Services\JwtAuth\JwtGenerator'

  App\Services\JwtAuth\ExtractPayloadInterface: '@App\Services\JwtAuth\JwtGenerator'