services:
  App\Services\ServicesGenerator:
    calls:
      - [setLogger, ['@logger']]
    decoration_priority: 1

  App\Services\ServicesGeneratorNew:

  app.service_generator: '@App\Services\ServicesGenerator'

  App\Services\ServicesGeneratorInterface: '@App\Services\ServicesGeneratorNew'


  App\Api\ParamConverter\StreetParamConverter:
    tags:
      - { name: request.param_converter, converter: get_street }
    arguments:
      - '@App\Repository\StreetRepository'

  App\Services\Security\TokenAuthenticator:
    arguments:
      - '@App\Repository\UserRepository'